// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfThYcpWNFs1hXV2T0Ug9Q0Fwb4G2KMJo',
    appId: '1:456310101334:web:6f7b01d7a330093b6732f7',
    messagingSenderId: '456310101334',
    projectId: 'ahedtest-29555',
    authDomain: 'ahedtest-29555.firebaseapp.com',
    storageBucket: 'ahedtest-29555.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRckF737nDjfkt7ItZY13hBE5p7SSXSSk',
    appId: '1:456310101334:android:609b5578fbc935b56732f7',
    messagingSenderId: '456310101334',
    projectId: 'ahedtest-29555',
    storageBucket: 'ahedtest-29555.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMNsFcB1UziMgfFzouPCVHlaLgTWIX8YA',
    appId: '1:456310101334:ios:0427fbaa06ca659c6732f7',
    messagingSenderId: '456310101334',
    projectId: 'ahedtest-29555',
    storageBucket: 'ahedtest-29555.appspot.com',
    iosClientId: '456310101334-pucveajv1gg5oe0vtm66crp0i52gouun.apps.googleusercontent.com',
    iosBundleId: 'com.example.authFirebase',
  );
}
